### PR TITLE
Mega quest additions

### PR DESCRIPTION
**Pull request by bschultz**
- Fix mega resource info
- Add support for MegaEvoPokemon condition

(I don't know why github shows such a huge diff for pokestop.js. Local diff looks fine 🤷‍♂️ )
Screenshot 2020-09-05 at 03 08 48

### CODE REVIEW

**Comment by versx** [comment]
I think it might be from line endings changed from Windows to Unix or vise versa. Looks good though.

**Comment by versx** [comment]
Hmm getting this :thinking: 
image

**Comment by bschultz** [comment]
> Hmm getting this 🤔
> image

Did you run `npm update pogo-protos`?

**Comment by versx** [comment]
> > Hmm getting this 🤔
> > image
> 
> Did you run `npm update pogo-protos`?

I did not, thank you!

**Pull request merged**
